swagger: '2.0'
info:
  version: '1.0'
  title: Delete Room Type
  description: API to delete a room type by ID
paths:
  /room_type/{id}:
    delete:
      tags:
        - Room Type
      summary: Delete Room Type
      description: Delete a specific Room Type by its ID
      operationId: deleteRoomTypeById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the Room Type to delete
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: Room Type deleted successfully
        '404':
          description: Room Type not found
          schema:
            $ref: '#/definitions/NotFoundError'

definitions:
  NotFoundError:
    type: object
    properties:
      message:
        type: string
        description: Error message for 'Not Found'
        example: Room Type not found
      code:
        type: integer
        format: int64
        description: Error code
        example: 404
