swagger: '2.0'
info:
  version: '1.0'
  title: Update Room Type API
  description: API to update Room Type information
paths:
  /room_type/{id}:
    put:
      tags:
        - Room Type
      summary: Update Room Type by ID
      description: Update a specific Room Type by its ID
      operationId: updateRoomTypeById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the Room Type to update
          required: true
          type: integer
          format: int64
        - name: roomType
          in: body
          description: Room Type object with updated information
          required: true
          schema:
            $ref: '#/definitions/RoomType'
      responses:
        '200':
          description: Successful response with the updated Room Type
          schema:
            $ref: '#/definitions/RoomType'
        '404':
          description: Room Type not found
          schema:
            $ref: '#/definitions/NotFoundError'

definitions:
  RoomType:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Unique identifier for the Room Type
      name:
        type: string
        description: Name of the Room Type
      description:
        type: string
        description: Description of the Room Type
      created_at:
        type: string
        format: date-time
        description: Date and time of Room Type creation
      updated_at:
        type: string
        format: date-time
        description: Date and time of last Room Type update
      price:
        type: integer
        format: int64
        description: Price of the Room Type
      status:
        type: string
        description: Status of the Room Type (e.g., 'active', 'inactive')

  NotFoundError:
    type: object
    properties:
      message:
        type: string
        description: Error message
        example: Not Found
      code:
        type: integer
        format: int64
        description: Error code
        example: 404
