swagger: '2.0'
info:
  description: Retrieve reservation details
  version: '1.0.0'
  title: Get Reservation Details

paths:
  /fetch:
    get:
      tags:
        - Reservation
      summary: Retrieve reservation details
      description: Endpoint to get reservation details
      operationId: getReservation
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: block_id
          description: Block ID
          required: true
          type: string
        - in: query
          name: room_type_id
          description: Room type ID
          required: true
          type: string

      responses:
        '200':
          description: Successful response with reservation details
          schema:
            $ref: '#/definitions/Reservation'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

definitions:
  Reservation:
    type: object
    properties:
      reservation_id:
        type: string
        description: Unique identifier for the reservation
      block_id:
        type: string
        description: ID of the block
      room_type_id:
        type: string
        description: ID of the room type
      created_at:
        type: date
        description: date and time of creation
      updated_at:
        type: string
        format: date
        description: date and time of last update
      no_of_reserve_bed:
        type: integer
        format: date
        description: total number of reserve beds
     s
