swagger: '2.0'
info:
  description: 'This is the documentation for the payment information'
  version: '1.0.0'
  title: 'Payment information'

paths:
  /paymentInfo/{booking_id}:
    get:
      tags:
        - Payment
      summary: Get payment information by booking ID
      description: Retrieve payment information for a specific booking ID
      operationId: getPaymentInfoByBookingId
      produces:
        - application/json
      parameters:
        - name: booking_id
          in: path
          description: ID of the booking to retrieve payment information
          required: true
          type: string
      responses:
        '200':
          description: Successful response with payment information
          schema:
            $ref: '#/definitions/PaymentInfo'
        '404':
          description: Payment information not found
          schema:
            $ref: '#/definitions/NotFoundError'

definitions:
  PaymentInfo:
    type: object
    properties:
      booking_id:
        type: string
        description: Unique identifier for the booking
      amount:
        type: number
        description: Payment amount
      method:
        type: string
        description: Payment method (e.g., credit card, cash)
      status:
        type: string
        description: Payment status (e.g., 'paid', 'pending')
      date:
          type: string
          description: Date of payment
