swagger: '2.0'
info:
  version: '1.0'
  title: Get all students
  description: API to retrieve all student information
paths:
  /students:
    get:
      tags:
        - Students
      summary: Get all students
      description: Retrieve all available students
      operationId: getAllStudents
      produces:
        - application/json
      responses:
        '200':
          description: Successful response with a list of students
          schema:
            type: array
            items:
              $ref: '#/definitions/Student'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/NotFoundError'

definitions:
  Student:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the student
      first_name:
        type: string
        description: First name of the student
      last_name:
        type: string
        description: Last name of the student
      date_of_birth:
        type: string
        format: date
        description: Date of birth of the student
      gender:
        type: string
        description: Gender of the student
      student_number:
        type: string
        description: Student number
      email:
        type: string
        description: Email of the student
      phone:
        type: string
        description: Phone number of the student
      status:
        type: string
        description: Status of the student (e.g., 'active', 'inactive')
      created_at:
        type: string
        format: date-time
        description: Date and time of student creation
      updated_at:
        type: string
        format: date-time
        description: Date and time of last student update

  NotFoundError:
    type: object
    properties:
      message:
        type: string
        description: Error message for 'Not Found'
        example: Student not found
      code:
        type: integer
        format: int64
        description: Error code
        example: 404
