swagger: '2.0'
info:
  version: '1.0'
  title: Delete a Student
  description: API to delete a student by ID
paths:
  /students/{id}:
    delete:
      tags:
        - Students
      summary: Delete a student by ID
      description: Delete a student from the system by their ID
      operationId: deleteStudentById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the student to delete
          required: true
          type: string
      responses:
        '204':
          description: Successful response, student deleted
        '404':
          description: Student not found
          schema:
            $ref: '#/definitions/NotFoundError'

definitions:
  NotFoundError:
    type: object
    properties:
      message:
        type: string
        description: Error message for 'Not Found'
        example: Student not found
      code:
        type: integer
        format: int64
        description: Error code
        example: 404
