swagger: '2.0'
info:
  version: '1.0'
  title: Create a Student
  description: API to create a new student
paths:
  /students:
    post:
      tags:
        - Students
      summary: Create a new student
      description: Add a new student to the system
      operationId: createStudent
      produces:
        - application/json
      parameters:
        - name: student
          in: body
          description: New student object
          required: true
          schema:
            $ref: '#/definitions/Student'
      responses:
        '201':
          description: Successful response with the created student
          schema:
            $ref: '#/definitions/Student'
        '400':
          description: Bad request, invalid input
          schema:
            $ref: '#/definitions/BadRequestError'

definitions:
  Student:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the Student
      first_name:
        type: string
        description: First name of the Student
      last_name:
        type: string
        description: Last name of the Student
      other_name:
        type: string
        description: Other name of the Student
      date_of_birth:
        type: string
        format: date
        description: Date of birth of the Student
      level:
        type: string
        description: Student level

      gender:
        type: string
        description: Gender of the Student
      student_number:
        type: string
        description: Student number
      email:
        type: string
        description: Email of the Student
      phone:
        type: string
        description: Phone number of the Student
      address:
        type: string
        description: Address of the Student
      guardian_name:
        type: string
        description: Guardian name of the Student
      guardian_phone:
        type: string
        description: Guardian phone number of the Student
      disability:
        type: string
        description: Disability of the Student
      created_at:
        type: string
        format: date-time
        description: Date and time of Student creation
      updated_at:
        type: string
        format: date-time
        description: Date and time of last Student update


  BadRequestError:
    type: object
    properties:
      message:
        type: string
        description: Error message for bad request
        example: Invalid input
