swagger: '2.0'
info:
  version: '1.0'
  title: Update a Student
  description: API to update student information by ID
paths:
  /students/{id}:
    put:
      tags:
        - Students
      summary: Update a student by ID
      description: Update an existing student's information by their ID
      operationId: updateStudentById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the student to update
          required: true
          type: string
        - name: student
          in: body
          description: Updated student object
          required: true
          schema:
            $ref: '#/definitions/Student'
      responses:
        '200':
          description: Successful response with the updated student
          schema:
            $ref: '#/definitions/Student'
        '400':
          description: Invalid input
          schema:
            $ref: '#/definitions/BadRequestError'
        '404':
          description: Student not found
          schema:
            $ref: '#/definitions/NotFoundError'

definitions:
  Student:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the Student
      first_name:
        type: string
        description: First name of the Student
      last_name:
        type: string
        description: Last name of the Student
      other_name:
        type: string
        description: Other name of the Student
      date_of_birth:
        type: string
        format: date
        description: Date of birth of the Student
      level:
        type: string
        description: Student level

      gender:
        type: string
        description: Gender of the Student
      student_number:
        type: string
        description: Student number
      email:
        type: string
        description: Email of the Student
      phone:
        type: string
        description: Phone number of the Student
      address:
        type: string
        description: Address of the Student
      guardian_name:
        type: string
        description: Guardian name of the Student
      guardian_phone:
        type: string
        description: Guardian phone number of the Student
      disability:
        type: string
        description: Disability of the Student
      created_at:
        type: string
        format: date-time
        description: Date and time of Student creation
      updated_at:
        type: string
        format: date-time
        description: Date and time of last Student update

  BadRequestError:
    type: object
    properties:
      message:
        type: string
        description: Error message for bad request
        example: Invalid input

  NotFoundError:
    type: object
    properties:
      message:
        type: string
        description: Error message for 'Not Found'
        example: Student not found
      code:
        type: integer
        format: int64
        description: Error code
        example: 404
