swagger: '2.0'
info:
  version: '1.0'
  title: Update Staff Information
  description: API to update staff information by ID
paths:
  /staff/{id}:
    put:
      tags:
        - Staff
      summary: Update Staff Information
      description: Update a specific Staff's information by its ID
      operationId: updateStaffById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the Staff to update
          required: true
          type: integer
          format: int64
        - name: updatedStaff
          in: body
          description: Updated Staff information
          required: true
          schema:
            $ref: '#/definitions/Staff'
      responses:
        '200':
          description: Successful response with the updated Staff information
          schema:
            $ref: '#/definitions/Staff'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequestError'
        '404':
          description: Staff not found
          schema:
            $ref: '#/definitions/NotFoundError'

definitions:
  Staff:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Unique identifier for the Staff
      name:
        type: string
        description: Name of the Staff
      phone:
        type: string
        description: Phone number of the Staff
      email:
        type: string
        description: Email of the Staff
      status:
        type: string
        description: Status of the Staff (e.g., 'active', 'inactive')
      created_at:
        type: string
        format: date-time
        description: Date and time of Staff creation
      updated_at:
        type: string
        format: date-time
        description: Date and time of last Staff update

  BadRequestError:
    type: object
    properties:
      message:
        type: string
        description: Error message for a bad request

  NotFoundError:
    type: object
    properties:
      message:
        type: string
        description: Error message for 'Not Found'
        example: Staff not found
      code:
        type: integer
        format: int64
        description: Error code
        example: 404
